[build]
  publish = "build"
  command = "bash ./scripts/build.sh"

[[headers]]
  for = "/_/_placeholder/*.png"
  [headers.values]
    Cache-Control = "public, max-age: 900, s-maxage=3600, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age: 900, s-maxage=604800, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/domains.json"
  [headers.values]
    Cache-Control = "public, max-age: 900, s-maxage=604800, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "https://github.com/home-assistant/brands"
  force = true
  status = 301

[[redirects]]
  from = "/_/*/:image"
  to = "/_/_placeholder/:image"
  force = false
  status = 302

[[redirects]]
  from = "/brands/_/*/:image"
  to = "/brands/_/_placeholder/:image"
  force = false
  status = 302
